(azureml_py310_sdkv2) azureuser@shekharh1002025:/mnt/batch/tasks/shared/LS_root/mounts/clusters/shekharh1002025/code/Users/shekhar_icd/src/model$ torchrun --nproc_per_node=2 optimized_training_script_v4.py
W0813 17:11:19.647000 16940 site-packages/torch/distributed/run.py:766] 
W0813 17:11:19.647000 16940 site-packages/torch/distributed/run.py:766] *****************************************
W0813 17:11:19.647000 16940 site-packages/torch/distributed/run.py:766] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
W0813 17:11:19.647000 16940 site-packages/torch/distributed/run.py:766] *****************************************
[W813 17:11:19.013484144 socket.cpp:200] [c10d] The hostname of the client socket cannot be retrieved. err=-3
[W813 17:11:19.017024470 socket.cpp:200] [c10d] The hostname of the client socket cannot be retrieved. err=-3
Load Parameters
Load Parameters
Loading Datasets
Loading Datasets
Loading dataset shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 18/18 [00:00<00:00, 29.81it/s]
Loading dataset shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 18/18 [00:00<00:00, 27.04it/s]
Setting Up Dataloader Num Workers & PIN Meory Flag
Setting Up Dataloader Num Workers & PIN Meory Flag
Recommended dataloader_num_workers : 6
AVAILABLE_MEMORY_GB : 620.7482414245605 | DATASET_MEMORY_SIZE_GB : 8.103603198051452 pin_memory : True
Datasets Loaded
..............
Loading Model e5-large-v2
Recommended dataloader_num_workers : 6
AVAILABLE_MEMORY_GB : 620.7441787719727 | DATASET_MEMORY_SIZE_GB : 8.103603198051452 pin_memory : True
Datasets Loaded
..............
Loading Model e5-large-v2
e5-large-v2 Model Initialized
...........
Initalizing Loss : MNR
Loss Initialized
..............
Initializing Optimizer
Learning Rate Scheduler Selected : cosine
Load Sentence Transformer Training Arguments
e5-large-v2 Model Initialized
...........
Initalizing Loss : MNR
Loss Initialized
..............
Initializing Optimizer
Learning Rate Scheduler Selected : cosine
Load Sentence Transformer Training Arguments
Traceback (most recent call last):
Traceback (most recent call last):
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/shekharh1002025/code/Users/shekhar_icd/src/model/optimized_training_script_v4.py", line 449, in <module>
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/shekharh1002025/code/Users/shekhar_icd/src/model/optimized_training_script_v4.py", line 449, in <module>
        main(config, date_time)main(config, date_time)

  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/shekharh1002025/code/Users/shekhar_icd/src/model/optimized_training_script_v4.py", line 384, in main
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/shekharh1002025/code/Users/shekhar_icd/src/model/optimized_training_script_v4.py", line 384, in main
    args = get_SentenceTransformerTrainingArguments(config)    
args = get_SentenceTransformerTrainingArguments(config)  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/shekharh1002025/code/Users/shekhar_icd/src/model/optimized_training_script_v4.py", line 260, in get_SentenceTransformerTrainingArguments

  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/shekharh1002025/code/Users/shekhar_icd/src/model/optimized_training_script_v4.py", line 260, in get_SentenceTransformerTrainingArguments
        args = SentenceTransformerTrainingArguments(args = SentenceTransformerTrainingArguments(

TypeErrorTypeError: : SentenceTransformerTrainingArguments.__init__() got an unexpected keyword argument 'pad_to_multiple_of'SentenceTransformerTrainingArguments.__init__() got an unexpected keyword argument 'pad_to_multiple_of'

W0813 17:12:29.166000 16940 site-packages/torch/distributed/elastic/multiprocessing/api.py:900] Sending process 17006 closing signal SIGTERM
E0813 17:12:29.280000 16940 site-packages/torch/distributed/elastic/multiprocessing/api.py:874] failed (exitcode: 1) local_rank: 0 (pid: 17005) of binary: /anaconda/envs/azureml_py310_sdkv2/bin/python
Traceback (most recent call last):
  File "/anaconda/envs/azureml_py310_sdkv2/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 355, in wrapper
    return f(*args, **kwargs)
  File "/anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/torch/distributed/run.py", line 892, in main
    run(args)
  File "/anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/torch/distributed/run.py", line 883, in run
    elastic_launch(
  File "/anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 139, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 270, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
optimized_training_script_v4.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2025-08-13_17:12:29
  host      : localhost
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 17005)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
(azureml_py310_sdkv2) azureuser@shekharh1002025:/mnt/batch/tasks/shared/LS_root/mounts/clusters/shekharh1002025/code/Users/shekhar_icd/src/model$ 
